### ISSUE TITLE
Collections and relationships

### ISSUE THREAD

**Issue by eiktyrner** [danieldunderfelt/mobx-app#1]
Say that I have two collections (movies and actors) that I want to populate with a json blob. 

I've got two scenarios 

1. Add everything at the same time from a nested json
2. Add the relationship later (after both objects are created) from the UI

Could you show some action examples of how that might look? 
I'm guessing I'd want an `addActor` action in my movies action factory that take a reference to an actor and a movie and does an update? 

Also, is there usually a one to one mapping between a store factory and a action factory? 
So I'd have a MovieStore and a MovieActions, but then MovieActions can be composed of more generic actions?

It's a bit of a mental shift going from OOP style Mobx to this but I think it is worth it in the end. It's like a middle ground in moving to Elm...

**Comment by danieldunderfelt** [comment]
Hi! Congrats on #1 and good question!

I would go with number 1. You didn't specify how your JSON is nested, but let's assume it's something like this:

```json
{
  "movies": [
    {
      "id": "a-movie",
      "title": "A movie",
      "actors": [ "actor1", "actor2" ]
    } ... more movies
  ],
  "actors": [
    {
      "id": "actor1",
      "name": "Actor One",
      "stars_in": ["a-movie"]
    } ... more actors
  ]
}
```

Here a reference to the movie is stored on actors that star in it and a reference to the actors are stored in the movies.

Now you want to add the movies to a `moviesCollection` and your actors to an `actorsCollection`:

```javascript
const state = observable({ movies: [], actors: [] })

// Run each movie through a Movie factory where you can implement movie-specific logic.
// Also pass the whole state so that it can be linked to actors. Explained below.
const movies = collection(state.movies, movie => Movie(movie, state))
movies.addItems(data.movies) // data is the json blob above

// Run actors through an Actor factory to enable their logic. Also explained below.
const actors = collection(state.actors, actor => Actor(actor, state))
actors.addItems(state.actors) // data is the json blob above
```

Right, now we have an observable array each for our actors and our movies in the state. *Now to actually answer your question:*

The relationships can easily be done with `computed` properties. So create factories for the movies and actors that contain their logic:

```javascript
function Movie(movieData, state) {
  const movie = observable({
    // computed property
    get actorsInMovie() {
      // find the actors that star in this movie
      return state.actors.filter(actor => actor.stars_in.indexOf(movieData.id) > -1)
    }
  })

  // add data from the json
  extendObservable(movie, movieData)

  return movie
}

function Actor(actorData, state) {
  const actor = observable({
    // computed property
    get starredInMovies() {
      // find the movies this actor has starred in
      return state.movies.filter(movie => movie.actors.indexOf(actorData.id) > -1)
    }
  })

  // add data from the json
  extendObservable(actor, actorData)

  return actor
}
```

So now the computed properties will always return what movies an actor has starred in or what actors a movie has. This is of course assuming your json is nested like this.

Example action that fetches data:

```javascript
const fetchMoviesAndActors = action(async () => {
  const dataResponse = await fetch('https://yourbackend.com/api/movies-and-actors')
  const data = await dataResponse.json()

  movies.addItems(_.get(data, 'movies', [])) // lodash for sanity
  actors.addItems(_.get(data, 'actors', [])) // lodash for sanity
})
```

I want to highlight that `collection` from this module is only a bit of sugar to help with creating and maintaining collections like these. It exists because I wanted to easily remove duplicate items and use "model" factories like these. The same thing can be easily achieved without `mobx-app`, just map over the data and push them onto the observable arrays.

**Comment by eiktyrner** [comment]
Thanks for the great reply. That clears up a lot of things!
It also opens up a few questions regarding organization. 

In the `fetchMoviesAndActors` action I wouldn't necessarily have direct access to both collections, they most likely wont be in the same file. At the moment it's an action in my moviesActions factory.

So do I import the actorActions factory into my movieActions factory since it's already defined in there with an addItems function?

I'm guessing this will lead to some circular dependencies between my action factories as the app grows and they all need to "reach" into each other?

Maybe a small section about file/folder structure would be a nice addition to the docs. Right now I've organized my files into actions/models/stores folders.

**Comment by danieldunderfelt** [comment]
No you don't need to cross-import the action factories.

in `movieActions.js`:

```javascript
export default state => {

  // Instantiate movies collection with Movie model and give the whole state to the model.
  const movies = collection(state.movies, movieData => Movie(movieData, state))

  const fetchMovies = action(async () => {
    const dataResponse = await fetch('https://yourbackend.com/api/movies')
    const data = await dataResponse.json()

    movies.addItems(_.get(data, 'movies', []))
  })

  return { fetchMovies }
}
```

And then the same in `actorActions.js`:

```javascript
export default state => {

  // Instantiate actors collection with Actor model and give the whole state to the model.
  const actors = collection(state.actors, actorData => Actor(actorData, state))

  const fetchActors = action(async () => {
    const dataResponse = await fetch('https://yourbackend.com/api/actors')
    const data = await dataResponse.json()

    actors.addItems(_.get(data, 'actors', []))
  })

  return { fetchActors }
}
```

And the rest of the examples from my previous reply will continue to work as before. By having the state as a singular observable object we can instantiate these action factories anywhere and link models through computed properties.

**Comment by eiktyrner** [comment]
I guess that works. I would need to split a few endpoints that return nested data and figure out how to wait on multiple actions until I render (I want a loading screen until all fetches are done) but I could probably manage that. It does increase the amount of http requests though by quite a bit if each collection need their own fetch instead of having one fetch that can update multiple collections. But I can live with that for now.

**Comment by danieldunderfelt** [comment]
Well my first fetch example fetched the nested json into both collections. Just put it in `movieActions`, create both `movieCollection` and `actorCollection` there for it to use and call it a day.

To solve your loading problem, modify the state structure as follows:

```javascript
const state = observable({
  movies: {
    items: [],
    loading: false
  },
  actors: {
    items: [],
    loading: false
  },
  // Computed property to combine loading states of both resources
  get isLoading() {
    return state.movies.loading || state.actors.loading
  }
})
```

If you have a single fetch function you can combine the two loading states into one, but this is good for more control. Then, flip them on or off when you fetch:

```javascript
const fetchMoviesAndActors = async () => {
  runInAction(() => {
    state.movies.loading = true
    state.movies.loading = true
  })

  const dataResponse = await fetch('https://yourbackend.com/api/movies-and-actors')
  const data = await dataResponse.json()

  // Yes, feel free to create both collections in movieActions
  movies.addItems(_.get(data, 'movies', [])) // lodash for sanity
  actors.addItems(_.get(data, 'actors', [])) // lodash for sanity

  // Flip back when done. This is an async function so this will run after
  // your requests have completed.
  runInAction(() => {
    state.movies.loading = false
    state.movies.loading = false
  })
}
```

Now just use that `isLoading` prop in the state to render a loading indicator!

**Comment by XPD-Kasun** [comment]
This is a great way. But if we lazy load these movies and actors, how we adapt this approach. For instance say, only a portion of movies and actors are loaded from the server. In this case, there might be stale relationships which returns null from computed property but actual data do reside in the server. Is there a way to extend this approach for handling lazy loaded relationships?

**Comment by danieldunderfelt** [comment]
@XPD-Kasun Hi! Sorry for the late reply.

I don't see lazy loading as a separate problem, you'll just need to find ways to invalidate the items in the collection if needed. Also, did you know about the second argument of `addItems`? It specifies the property of each item that should be unique in the collection, like an id: `collection.addItems(items, 'id')`. Now double items won't be added. It will favor the item that's already in the collection, but I may publish some changes to this in the future.
