### ISSUE TITLE
Don't import whole lodash

### ISSUE THREAD

**Issue by srigi** [danieldunderfelt/mobx-app#2]
You're importing whole `lodash` module in your sources just to call one or two methods of it.
Either import individual packages (`lodash.forown`, `lodash.pick`) or import like 

```js
import pick from 'lodash/pick'
```

Otherwise users of this library are penalised that their bundle.js contains whole lodash.js even if they're not using it.

**Comment by danieldunderfelt** [comment]
...there are users of this library?

This is an excellent idea though, and I should have done it from the start. Not sure if I will update this library anymore though.

**Comment by srigi** [comment]
@danieldunderfelt  _...there are users of this library?_

Yes, I'm using it, I hate to write OOP code in React. This lib. helps avoiding that a lot.

I think this lib. is complete & finished. But this little issue should be resolved. If you're out of time, I can send PR later next week.

**Comment by danieldunderfelt** [comment]
Wow! Glad you like it!

Yeah send a PR and I'll get it merged.

**Comment by srigi** [comment]
@danieldunderfelt Hi, can you give any feedback on #3?
