### ISSUE TITLE
How to go about computed fields?

### ISSUE THREAD

**Issue by marano** [danieldunderfelt/mobx-app#4]
Hello!

I am starting with mobx and I am glad I came across this, this architecture is exactly what I have been looking for.

Just one thing is not very clear to me yet, how should I go about adding computed values? I found nothing on this on the Readme. Should I add computed getters as actions?

Thank you in advance!

**Comment by nielsrowinbik** [comment]
I check this repo every now and then to remind myself of the API and saw your issue hadn't been answered yet, so here you go!

Actions will deliberatly change the state, but computed values just "make up" the state if you will. I suggest reading the [MobX documentation.](https://mobx.js.org/index.html) To answer your question, you can use MobX's `computed` decorator in conjunction with this library like so:

```js
import { computed, extendObservable } from 'mobx';

const SomeStore = (state, initial) => {

    extendObservable(state, {
        someValue: computed(() => {
            // compute value here and return it
        })
    });

    // other code in your store
};
```

**Comment by danieldunderfelt** [comment]
@marano @nielsrowinbik Hi, I'm really sorry about not being too active here. I got to get better at this! I never thought this would have actual other users than me 😅

Thanks Niels for replying. A core idea here is to not hide MobX in any way, so just use MobX like normal. If you're not previously familiar with MobX, you absolutely need to read it's docs! Mobx-app is just a few utility functions and an idea of how to use MobX in a smooth manner.
