### ISSUE TITLE
error in the async action

### ISSUE THREAD

**Issue by sallespro** [danieldunderfelt/mobx-app#5]
trying the example async action, but it returns

`Uncaught (in promise) TypeError: newItems.map is not a function`

```
    async function fetchItems(params) {
        const newItems = await fetch('https://jsonplaceholder.typicode.com/users')
        replaceItems(newItems)
    }
```

**Comment by sallespro** [comment]
oops. missing ` await dataResponse.json()`

**Comment by danieldunderfelt** [comment]
Hehe 😉 That one will bite you in the butt occasionally.

To be clear, the v1 async stores feature only concerns STORE FACTORIES, which can now return promises. Put another way, they can return their actions asynchronously. It has always been possible to return promises from the actions themselves.

**Comment by danieldunderfelt** [comment]
I didn't notice this was actually from the README, I thought you were inspired by the recent release notes. My mistake! Fixed the README example.
